makeCacheMatrix <- function(x = matrix()) {
                m <- NULL ## initializing matrix
                set <- function(y){
                        x <<- y
                        m <<- NULL
                }
                get <- function() ##define the return matrix
                        x ##return special matrix
                setInv <- function(inverse) m <<- inverse ##assigning inverse matrix 
                getInv <- function() ##define function for returning the inverse matrix
                        m
                list(set = set, ##all defined functions in list 
                     get = get,
                     setInv = setInv,
                     getInv = getInv)
}


## Write a short comment describing this function
## Return a matrix that is the inverse of 'x'
cacheSolve <- function(x, ...) {
        m <- x$getInv() ##get inverse of the original matrix generated by makeCacheMatrix
        if (!is.null(m)){ ##Verify if the inverse has already been computed
                message("getting cached data")
                return(m)
        }
        data <- x$get()
        m <- solve(data, ...)
        x$setInv(m)
        m
}
